language: php

php:
  - 7.1
  - 7.2

before_script:
  - cp .env.example .env
  - composer self-update
  - composer install --no-progress --no-interaction --prefer-dist --no-suggest
  - php artisan key:generate

script: vendor/bin/phpunit --verbose